name: Mega Sena Predictor Scheduler

# Adiciona o agendamento E o gatilho manual
on:
  schedule:
    # Rodar às 22:00 BRT/BRST
    - cron: '0 1 * * 3,6' 
  
  # ESTE BLOCO ATIVA O BOTÃO "Run workflow" NO PAINEL DE AÇÕES
  workflow_dispatch: 
    # (Não precisa de parâmetros aqui)

jobs:
  run_script:
    # Usar um runner Ubuntu no GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a versão mais recente do Python 3
        
    - name: Install Dependencies (Poetry)
      run: |
        pip install poetry
        poetry install --no-root
        
    - name: Run Prediction Script
      env:
        # Configura as variáveis de ambiente do Telegram
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
      run: poetry run python predictor.py
